import { ProfileKey } from "@/types/profile";

export interface PatternEntry {
  readonly key: ProfileKey;
  readonly patterns: readonly RegExp[];
  readonly autocomplete: readonly string[];
  readonly inputTypes: readonly string[];
}

export const PATTERN_DICTIONARY: readonly PatternEntry[] = [
  {
    key: "email",
    patterns: [
      /e[-_.]?mail/i,
      /e-?mail\s*address/i,
      /이메일/,
      /메일\s*주소/,
      /전자\s*우편/,
    ],
    autocomplete: ["email"],
    inputTypes: ["email"],
  },
  {
    key: "phone",
    patterns: [
      /phone/i,
      /tel(?:ephone)?/i,
      /mobile/i,
      /cell/i,
      /전화/,
      /휴대폰/,
      /휴대\s*전화/,
      /연락처/,
      /핸드폰/,
      /\bHP\b/i,
      /연락\s*번호/,
    ],
    autocomplete: ["tel", "tel-national"],
    inputTypes: ["tel"],
  },
  {
    key: "fullName",
    patterns: [
      /full[-_.]?name/i,
      /your[-_.]?name/i,
      /^name$/i,
      /이름/,
      /성명/,
      /본명/,
    ],
    autocomplete: ["name"],
    inputTypes: [],
  },
  {
    key: "firstName",
    patterns: [
      /first[-_.]?name/i,
      /given[-_.]?name/i,
      /fname/i,
    ],
    autocomplete: ["given-name"],
    inputTypes: [],
  },
  {
    key: "lastName",
    patterns: [
      /last[-_.]?name/i,
      /sur[-_.]?name/i,
      /family[-_.]?name/i,
      /lname/i,
      /^성$/,
    ],
    autocomplete: ["family-name"],
    inputTypes: [],
  },
  {
    key: "birthDate",
    patterns: [
      /birth[-_.]?d(ay|ate)/i,
      /date[-_.]?of[-_.]?birth/i,
      /dob/i,
      /생년월일/,
      /생년/,
      /생일/,
    ],
    autocomplete: ["bday"],
    inputTypes: ["date"],
  },
  {
    key: "gender",
    patterns: [
      /gender/i,
      /sex/i,
      /성별/,
    ],
    autocomplete: ["sex"],
    inputTypes: [],
  },
  {
    key: "zipCode",
    patterns: [
      /zip[-_.]?code/i,
      /postal[-_.]?code/i,
      /post[-_.]?code/i,
      /우편\s*번호/,
    ],
    autocomplete: ["postal-code"],
    inputTypes: [],
  },
  {
    key: "address",
    patterns: [
      /^address$/i,
      /address[-_.]?1/i,
      /street[-_.]?address/i,
      /street/i,
      /addr/i,
      /^주소$/,
      /도로명/,
    ],
    autocomplete: ["address-line1", "street-address"],
    inputTypes: [],
  },
  {
    key: "addressDetail",
    patterns: [
      /address[-_.]?2/i,
      /apt/i,
      /suite/i,
      /unit/i,
      /상세\s*주소/,
      /나머지\s*주소/,
    ],
    autocomplete: ["address-line2"],
    inputTypes: [],
  },
  {
    key: "city",
    patterns: [
      /city/i,
      /town/i,
      /municipality/i,
      /시[·\s/]?군[·\s/]?구/,
      /도시/,
    ],
    autocomplete: ["address-level2"],
    inputTypes: [],
  },
  {
    key: "company",
    patterns: [
      /company/i,
      /organization/i,
      /employer/i,
      /firm/i,
      /회사/,
      /직장/,
      /소속/,
      /기관/,
    ],
    autocomplete: ["organization"],
    inputTypes: [],
  },
  {
    key: "department",
    patterns: [
      /department/i,
      /dept/i,
      /division/i,
      /부서/,
      /팀/,
    ],
    autocomplete: [],
    inputTypes: [],
  },
  {
    key: "position",
    patterns: [
      /position/i,
      /title/i,
      /role/i,
      /job[-_.]?title/i,
      /직책/,
      /직위/,
      /직급/,
    ],
    autocomplete: ["organization-title"],
    inputTypes: [],
  },
  {
    key: "career",
    patterns: [
      /career/i,
      /experience/i,
      /work[-_.]?history/i,
      /work\s*experience/i,
      /경력/,
      /경험/,
      /업무\s*경험/,
      /이력/,
    ],
    autocomplete: [],
    inputTypes: [],
  },
  {
    key: "selfIntro",
    patterns: [
      /self[-_.]?intro/i,
      /about[-_.]?(me|you(rself)?)?/i,
      /bio(graphy)?/i,
      /description/i,
      /summary/i,
      /cover[-_.]?letter/i,
      /motivation/i,
      /cover/i,
      /자기\s*소개/,
      /지원\s*동기/,
      /자기\s*PR/i,
      /소개/,
    ],
    autocomplete: [],
    inputTypes: [],
  },
  {
    key: "website",
    patterns: [
      /website/i,
      /homepage/i,
      /blog/i,
      /portfolio/i,
      /url/i,
      /웹사이트/,
      /홈페이지/,
      /블로그/,
      /포트폴리오/,
    ],
    autocomplete: ["url"],
    inputTypes: ["url"],
  },
  {
    key: "github",
    patterns: [
      /github/i,
      /git[-_.]?hub/i,
      /깃허브/,
    ],
    autocomplete: [],
    inputTypes: [],
  },
  {
    key: "linkedin",
    patterns: [
      /linkedin/i,
      /linked[-_.]?in/i,
      /링크드인/,
    ],
    autocomplete: [],
    inputTypes: [],
  },
];
